print('hello, world!')
print('nurap')
print('denise e seus remedios')
print('hj tem bolo de graca')
print('hj eu descobri que o messi joga bola')
print('spotifywrapped')
print('coxinha)
print('rebolativo')
print('jamal bieber')
print('GAGAMEL')